### ISSUE TITLE
ncremap "renormalization_threshold" vs "renormalize_threshold"

### ISSUE THREAD

**Issue by xylar** [nco/nco#164]
In the documentation and the help string, `ncremap` is said to have a option `renormalize_threshold`:
https://github.com/nco/nco/blob/master/data/ncremap#L530

But in actuality, the flag is `renormalization_threshold`:
https://github.com/nco/nco/blob/master/data/ncremap#L700

**Comment by czender** [comment]
Good catch! This is now fixed in master. I eliminated `renormalize_threshold` since it never worked. The two longest option synonyms are now `renormalize` and `renormalization_threshold`. BTW, the forthcoming NCO 4.9.0 adds a new option, `--preserve=mean|integral`, that is intended to be more intuitive than `--rnr_thr`.  The default, `--preserve=integral`, preserves the sum of the valid values in the source region. In conjunction with a conservative regridding algorithm it will yield a conservative result. It is equivallent to `--rnr_thr=none`. The non-default, `--preserve=mean`,  preserves the mean of the valid values in the source region. It is equivalent to `--rnr_thr=0.0`.  It is not conservative whenever there are missing values or fractional masks. It is non-default except for MPAS where for consistency with past practice it is the default. Any thoughts on these choices?

**Comment by xylar** [comment]
Sounds great.

The one thing I would request is that remapping not behave differently when a `_FillValue` attribute is present or not because that's causing me a lot of headache.  Or at least that there be a mode where that's the case.

As you will recall, I had set things us where I was writing out NetCDF files that only set the `_FillValue` attribute if there are actually missing values and leave it out otherwise.  But this has turned out not to play well with `ncremap` because it only puts fill values in after remapping if `_FillValue` is present before remapping.

**Comment by czender** [comment]
Yes, I removed the `_FillValue`-dependent behavior as we discussed.  Now renormalization is always opt-in, regardless of the presence/absence of missing values. Sorry for the headaches that resulted from the previous behavior.
