### ISSUE TITLE
ncclimo hourly data issue

### ISSUE THREAD

**Issue by tangq** [nco/nco#237]
I tried to use ncclimo to process the hourly data from year 2000 to 2009, but the output only covers 2000 to the middle of 2003. No errors or warnings.

The batch output log (ts_atm_hourly_180x360_aave_2000-2009-0010.o184062) shows that ncclimo was invoked with the correct input files, but the output file header info indicates that the input files were truncated at year 2003. I am not sure how this can happen.

The script is at compy:/compyfs/tang338/E3SM_simulations/20210326_chemUCI.beta1_01.amip.ne30pg2_r05_oECv3.compy/post/scripts/ts_atm_hourly_180x360_aave_2000-2009-0010.bash

The ncclimo command in the script is:
ncclimo \
-c 20210326_chemUCI.beta1_01.amip.ne30pg2_r05_oECv3.compy \
-v O3_SRF \
--yr_srt=2000 \
--yr_end=2009 \
--ypf=10 \
--map=/qfs/people/zender/data/maps/map_ne30pg2_to_cmip6_180x360_aave.20200201.nc \
-o trash \
-O output \
--clm_md=hfs \
--tpd=24 \
20210326_chemUCI.beta1_01.amip.ne30pg2_r05_oECv3.compy.eam.h1.????-*.nc

The output file is at: /compyfs/tang338/E3SM_simulations/20210326_chemUCI.beta1_01.amip.ne30pg2_r05_oECv3.compy/post/atm/180x360_aave/ts/hourly/10yr

**Comment by czender** [comment]
Thanks for the report, this is a good place to report. I'll take a look ASAP.

**Comment by czender** [comment]
Hi Qi,

ncclimo produces bad answers here because it makes two assumptions:

1. Unless otherwise specified, high frequency files contain 30 day per file
2. The first input file contains a timestep within the desired interval

At least one of these assumptions is false in your case.
Fix #1 is to tell ncclimo the number of days-per-file with the `--dpf=10` option.
If #2 is also false, please change the input file list accordingly.
These commands work for me:

```
drc_in=/compyfs/tang338/E3SM_simulations/20210326_chemUCI.beta1_01.amip.ne30pg2_r05_oECv3.compy/archive/atm/hist
drc_out=${DATA}/ne30/clm
drc_rgr=${DATA}/ne30/rgr
cd ${drc_in};ncclimo -v O3_SRF --clm_md=hfs --tpd=24 --dpf=10 -c hfs --yr_srt=2000 --yr_end=2009 --ypf=10 -o ${drc_out} -O ${drc_rgr} 20210326_chemUCI.beta1_01.amip.ne30pg2_r05_oECv3.compy.eam.h1.1999-12-27-*.nc 20210326_chemUCI.beta1_01.amip.ne30pg2_r05_oECv3.compy.eam.h1.200?-*.nc

```
Please let me know what happens when you add `--dpf=10`.

I can probably remove both assumptions from ncclimo.
That would take significant effort, though the resulting user-friendliest 
would probably be worth the effort.
But first let's make sure the above works for you.

Charlie

**Comment by tangq** [comment]
@czender , thanks for the quick reply. My 1-year test with the additional `--dpf=10` option is successful.

I added the additional options to zppy on this PR: https://github.com/E3SM-Project/zppy/pull/18.

zppy addes the last file of previous year and the first file on next year to the ncclimo input files. This satisfies the assumption 2 for my tests and most cases. But #2 will be false under one special case. That is when the the first record of the desired interval happens to be the first record of the first file of the beginning year.

If ncclimo can handle unnecessary input files prior to the beginning year (should be easier than removing both assumptions), with the above PR it seems sufficient for zppy for now.

**Comment by czender** [comment]
Glad to hear it works with the additional option. I think `ncclimo` will work fine when the first timestep of the first file is within the desired interval, so I think we're good. Or am I missing something? If so, can you please provide a counter-example?

**Comment by czender** [comment]
As it happens, I thought of that already and built-in one file of "forgiveness" into `ncclimo` when in high-frequency mode, so it should work when the first timestep is in the second file. I think `ncclimo` will fail if the first timestep is in the third file. LMK if you learn otherwise by re-opening this issue, which I'm now closing.
