### ISSUE TITLE
x10 error margin for the same spell after

### ISSUE THREAD

**Issue by rkouznetsov** [nco/nco#256]
Here is just a continuation of our discussion at EGU. The problem is that after a minor version update (5.0.2 to 5.0.3) the error I get with the same nco spell increased tenfold. 

![PrecisionEGU2022slides-ShownAtEGU2022](https://user-images.githubusercontent.com/11734464/172104121-8d3a5c5f-0dc0-4f84-ac8e-c8112b09b1ce.png)

rerr is the the maximum of absolute difference normalized with the original value.
comprr is just a resulting file size normalized with the original uncompressed size.
Here is the file used for calculation:
[sig53.nc.gz](https://github.com/nco/nco/files/8842195/sig53.nc.gz)
The full presentation can be found at http://silam.fmi.fi/roux/PrecisionEGU2022slides-ShownAtEGU2022.pdf (see also discussion a thttps://github.com/Unidata/netcdf-c/issues/2369)

I have been used to think that "precise within N decimals" means the relative error margin that guarantees exact representation of N decimals.  i.e. the maximum absolute error normalized with the exact value is within 5%, 0.5% 0.05% etc. for NSD=1,2,3 etc. It had been like that until v5.0.2 (half of that between 4.9.5 - 5.0.2). 

In v5.0.3, apparently, the meaning of  "precise within N decimals" was changed  to something that guarantees that first N places are kept if one _prints_ the value in decimal form. With the latter definition the allowed error is  x10 larger, and the error margin is very different for numbers around 0.1 and around 0.9...

I wonder if quiet x10 increase of an error obtained with the same spell is a desired feature in a general-purpose data-handling software. 

Formally,  v5.0.3 provides higher compression ratio for the same NSD, but should not the compression ratios be compared at the comparable error margin?

**Comment by czender** [comment]
Thank you for your analysis. NCO continually evolves, yet strives to make backwards compatibility possible. As you may know, you can obtain the same results you obtained previously by setting the `--baa` option as described in the manual. You are correct that the default method changed (to Granular BitRound) and the error for the same NSD increased about 10-fold. At the same time, the compression ratio (lower is better) improved from 0.38 to 0.30. 
The definition of what BitGroom and Granular BitRound are designed to preserve is `|raw-quantized| <= 0.5*10^{xpn-NSD}`, where xpn is the number of digits before the decimal separator when writing out the value in decimal, and NSD is the user-specified number of significant digits. Yes, this means that 9*10^x requires 3-4 bits more to preserve that guarantee than 1*10^x. As you can see, the guaranty is absolute not relative. It would indeed be nice to modify the quantization to preserve exact representation of N decimals as you suggest. The only reason that BitGrooming followed by BitRounding managed to do that was because the error tolerances for BitGrooming were (inadvertently) set to be much to strict.
I may add more here later. Gotta go now.

**Comment by rkouznetsov** [comment]
Thank you for the clarification, and giving the _new_ definition. I would appreciate if someone could provide me with any use-case where Granular BitRound is the optimal strategy, except for actual _printing_ decimals. So far I see no advantage but the confusion, and potentially dangerous consequences for those who did not introduce all these baa keys into their scripts and update nco.

I believe it is very handy to have, the _precision_  defined as a  _linear_ property. i.e. it is invariant with respect to addition and multiplication with a number.  If we have an array with NSD=2, and multiply it with some number, the result would still have NSD=2. If we have two arrays of NSD=2, the resulting array will have NSD=2. etc.  This property used to hold until the nde definition and Granular BitRound was introduced. 

I agree that after rounding was introduced instead of  BitGroom the NSD translation to NSB become too conservative. The reason was that  besides getting rid of the BitGroom artifacts (such as _unbound_ error in two-point statistics), the introduced error was halved, so one could actually use one bit less. It was, however, a safe change, since I could not find any single case where BitGroom had any advantages over rounding, and  after the update the error stayed within the earlier-set margins.

So in 5.0.3 the definition of decimal precision has been changed. Moreover, it was made a method-specific: different `baa` assume different definitions. As a result of tweaking the definition, one quietly gets x10 error from the same spell, and the same compression ratio as one would get by just explicitly ordering x10 higher error. Looks like getting an Opel with a Mercedes label as an updated and more affordable version of a Mercedes, doesn't it?

`nsb = ceil(3.32*NSD)` is something that has been already implemented in nco for rounding, if i interpret the code right. So there is no need to implement anything new.

As a way to go, instead of adding more to the already existing multitude of methods, translations from decimals to binary, and definitions of "decimal precision",  I would suggest to leave only bitRound, and make a table explicitly specifying the error margins and corresponding approximate number of decimals. Besides the main documentation, the table should the be replicated in "usage" and man pages. Of course, this braking change should be introduced on a major-version update.
Also some "lock-pin" should be introduced to the command syntax to make sure that no one gets quietly-redefined precision. 

I would start with introducing a precision-handling function in ncap2. Is there any template for a function that gets a variable and some other argument, and returns a variable of the same type?

**Comment by czender** [comment]
The method that @rkouznetsov likes (and that was NCO's default from default 20200717--20210928 is called "BitGroomBitRound". It is still available and invocable via 

`ncks -7 -L 1 --baa=5 --ppc default=3 in.nc out.nc # BitGroomBitRound (NSD).
`
Granular BitRound is invocable via 

`ncks -7 -L 1 --baa=4 --ppc default=3 in.nc out.nc # Granular BitRound (NSD)
`
and, since it is the current NCO default, via

`ncks -7 -L 1 --ppc default=3 in.nc out.nc # Granular BitRound (NSD)
`
and also, since NCO 5.1.0, via the netCDF implementation as

`ncks --cmp=gbr ...
`
There are no plans to make BitGroomBitRound the default again, so I am closing this issue as "wontfix"

**Comment by rkouznetsov** [comment]
Thank you, @czender  for your response!  The question here was not in _like_ or  _dislike_ specific methods. Each method is good in some cases and bad in some other. One just have to apply a method that best fits a specific case. I would be happy to discuss the areas of applicability of the methods elsewhere if someone wishes (e.g. https://github.com/Unidata/netcdf-c/discussions/2406).

  The question was  that a _silent_ x10 increase of the error margin after a minor-version update is, probably not a desired feature. It has broke a few things in our production environment and will keep doing so for next years, as production environments are slow to update. In our case it was quickly spotted and work-arounds have been applied. In other cases it might take longer to spot it.

Apparently, nco maintainers do not consider it as an issue, which is is a very valuable piece of information.
