### ISSUE TITLE
ncremap documentation clarification

### ISSUE THREAD

**Issue by cdholmes** [nco/nco#282]
The [documentation](https://nco.sourceforge.net/nco.html#ncremap) for `ncremap` is inconsistent about what the default algorithm is. 

In one place it says that `bilinear` is default (emphasis added):
> The seven ERWG weight generation algorithms are: bilinear (**default,** acceptable abbreviations are bilin, blin, bln)

In another place, it says that `nco_conservative` is default (emphasis added):
> This algorithm is built-in to NCO and requires no external software so it is the **default** weight generation algorithm

It would be nice to clear up this ambiguity in the docs. If `nco_conservative` is indeed the default, it might be clearer if the paragraphs describing `-a alg_typ` were rearranged to describe `nco_conservative` first.

Thanks for the very useful `ncremap`!

**Comment by czender** [comment]
Hi Chris, Thanks for reporting this overlooked contradiction. The short answer is that `nco_conservative` is the default and has been since it was released. To match new E3SM conventions we now prefer the synonym `ncoaave`. I am now updating the documentation to clarify, and will post again when that is ready.

**Comment by czender** [comment]
I've made a lot of updates to the online ncremap documentation. I'm sure it could be further improved. Let me know if you spot other problematic areas.
