### ISSUE TITLE
nco writes `_ChunkSizes` attributes to NetCDF3 files when getting from DAP

### ISSUE THREAD

**Issue by rkouznetsov** [nco/nco#284]
Today's master branch..
```
$ src/nco/ncks --version
NCO netCDF Operators version 5.2.5-alpha02 "Takumi Tonkatsu Ramen" built by kouzne on kouznetsov23l at Jun  5 2024 11:58:21
ncks version 5.2.5-alpha02

$ src/nco/ncks -v dd_POLLEN_GRASS_m32 -d time,1 https://thredds.silam.fmi.fi/thredds/dodsC/silam_europe_pollen_v5_9_1/runs/silam_europe_pollen_v5_9_1_RUN_2024-06-05T00:00:00Z out-525.nc
```
The resulting file is NetCDF3, but has `_ChunkSizes` attributes for dimesions.

If I request NerCDF4 output:
```
$ src/nco/ncks -4 -L5 -v dd_POLLEN_GRASS_m32 -d time,1 https://thredds.silam.fmi.fi/thredds/dodsC/silam_europe_pollen_v5_9_1/runs/silam_europe_pollen_v5_9_1_RUN_2024-06-05T00:00:00Z out-525.nc4

```
 the variables have two (Sic!) `_ChunkSizes`  attributes each... 
Is it a bug or a feature?

Thank you!

**Comment by czender** [comment]
Update: By using different software (`nccopy/ncdump` instead of `ncks`) and a different netCDF3 file downloaded from a different DAP server
(`nccopy http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ncep.reanalysis.dailyavgs/surface/pres.sfc.1969.nc ~/foo.nc`) I have verified that the behavior you observe appears to be present in any file downloaded with the DAP library that ships with the latest netCDF. It is not an NCO issue.

**Comment by rkouznetsov** [comment]
Thank you, Charlie! Looks like it is a feature:) OpenDAP people believe that it is a good idea to expose chunking information to DAP clients (https://github.com/Unidata/tds/issues/503#issuecomment-2148005181), and NetCDF people believe that it is a good idea to transfer all the attributes they get from DAP to a file..  I would say, that the problem is on the DAP side.

Indeed NCO is just in between these two: a convenient tool to acquire DAP server:) Thank you once again, and sorry for false alarm.
