### ISSUE TITLE
The CMake build don't take into account neither NETCDF_ROOT or HDF5_ROOT/HDF5_DIR

### ISSUE THREAD

**Issue by r3n4ud** [nco/nco#287]
Using the nco-5.2.8 release tarball.

Recent (maybe not so recent?) CMake releases leverage and standardize the path resolution used with `find_package`
(See  [the CMake find_package documention](https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure). Unfortunately, `find_package` is not used at all for hdf5 or netcdf resolution and the actual process to discover those libraries seems broken for custom/non standard location…

```
[…]
-- Using user-defined netCDF root location: /home/REDACTEDUSER/.local/opt/netcdf-c-4.9.2
-- Found netcdf.h header file at: /usr/include
-- Found netcdf library at: /usr/lib/x86_64-linux-gnu/libnetcdf.so
[…]
```

For whatever reason is mine, I'd like to use my custom netcdf and I can't.

Browsing the root `CMakeLists.txt`, it seems to me that there is a lot of useless code, considering that CMake can actually find those libraries by itself, using a now standard procedure (since CMake 3.12?).

Any plan on refreshing the CMake build? Do you accept PR on this? What are the current constraints to enforce (hdf5 and netcdf minimal requirements)?

**Comment by czender** [comment]
Hi, thank you for reporting your experiences with the CMake build. The CMake build was written nearly 10 years ago and has not been substantially updated since. I'm not a CMake expert so I would welcome any improvements/updates to the CMake system that make it do what you want without breaking it for others. This is an open source project that welcomes patches! 
 You can even assume that all users have a recent CMake. We value our future users as much as our past.

**Comment by czender** [comment]
Pinging @pedro-vicente in case he has anything to add about these CMake issues...

**Comment by pedro-vicente** [comment]
@czender I'll take a look. Maye take a few days

**Comment by czender** [comment]
Thanks @pedro-vicente . I'm about to release 5.2.9. Hopefully we can get a patch in time for 5.3.0.

**Comment by pedro-vicente** [comment]
@czender I'm doing this this weekend, I don't have my old email anymore, new one should be somewhere on this profile

**Comment by pedro-vicente** [comment]
@r3n4ud 

I think I was able to reproduce the issue that you reported

I built/installed netCDF at this location, and set this environment variable

`export NETCDF_ROOT=/Users/pvn/netcdf_install`

to build NCO with cmake

`cmake .. -DCMAKE_INSTALL_PREFIX=/Users/pvn/nco_install`

output

`-- Using user-defined netCDF root location: /Users/pvn/netcdf_install
-- Using /usr/local/include/netcdf.h
-- Found netcdf.h header file at: /usr/local/include
-- Using /usr/local/lib/libnetcdf.dylib
-- Found netcdf library at: /usr/local/lib/libnetcdf.dylib
`

So, what happens here is that a system installed netCDF was detected instead of my custom location

This is done in this part of the CMakeLists.txt


`if(NETCDF_INCLUDE)
  if(EXISTS "${NETCDF_INCLUDE}/netcdf.h")
    message("-- Using ${NETCDF_INCLUDE}/netcdf.h")
  else()
    if(netcdf_root)
      set(NETCDF_INCLUDE "${netcdf_root}/include")
    endif()
    if(EXISTS "${NETCDF_INCLUDE}/netcdf.h")
      message("-- Using ${NETCDF_INCLUDE}/netcdf.h")
    else()
      message(FATAL_ERROR "${color_red}netcdf.h not found at ${NETCDF_INCLUDE}${color_reset}")
    endif()
  endif()
endif()`


One way to solve this as a quick fix  is to uninstall the system installed netCDF , that way it seems, the if/else
above should use the  'netcdf_root' variable

A more permanent solution seems to be  to modify the if/else logic above to something like

`if(netcdf_root)
      set(NETCDF_INCLUDE "${netcdf_root}/include")
    endif()
else ( detect the system installed netCDF)
`

Is this something that you can try ?

**Comment by pedro-vicente** [comment]
@r3n4ud @czender 

A custom netCDF can be simply set with

`cmake .. -DCMAKE_INSTALL_PREFIX=/Users/pvn/nco_install -DNETCDF_INCLUDE=/Users/pvn/netcdf_install/include -DNETCDF_LIBRARY=/Users/pvn/netcdf_install/lib/libnetcdf.dylib`

```
-- Using /Users/pvn/netcdf_install/include/netcdf.h
-- Found netcdf.h header file at: /Users/pvn/netcdf_install/include
-- Using /Users/pvn/netcdf_install/lib/libnetcdf.dylib
-- Found netcdf library at: /Users/pvn/netcdf_install/lib/libnetcdf.dylib
```
