### ISSUE TITLE
Trying to install nco inside uvcdat

### ISSUE THREAD

**Issue by doutriaux1** [nco/nco#29]
if I try to install nco via conda inside of uvcdat, I have a conflict, I think this is due to nco being built against old hdf5/netcdf.
It appears that nco will `downgrade` our hdf5 but not our netcdf

quick summary, at nco install time:
`conda install nco -c ocnda-forge`

output warns about HDF5:

```
The following NEW packages will be INSTALLED:

    expat:  2.1.0-2       conda-forge
    gsl:    2.1-2         conda-forge
    krb5:   1.14.2-0      conda-forge
    libgcc: 4.8.5-1                  
    nco:    4.6.0-0       conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    hdf5:   1.8.16-UVCDAT uvcdat      --> 1.8.15.1-2
```

It goes through the motions but then cannot function:

```
((2016.9.14)) doutriaux1@sofia:[~]:[6605]> ncks --help
dyld: Library not loaded: @rpath/libhdf5.10.dylib
  Referenced from: /Users/doutriaux1/anaconda2/envs/2016.9.14/lib/libnetcdf.7.dylib
  Reason: Incompatible library version: libnetcdf.7.dylib requires version 12.0.0 or later, but libhdf5.10.dylib provides version 11.0.0
Trace/BPT trap: 5
```

**Comment by czender** [comment]
Hi Charles,
Although I am not a conda expert your diagnosis makes sense to me. Others, primarily @ocefpaf, maintain the NCO feedstock, so this message will alert them. It sounds like the solution is to update the NCO feedstock (to hdf5 1.8.16), or something like that? @ocefpaf, @doutriaux1 wants to load NCO within the UVCDAT conda package. The NCO feedstock is [here](https://github.com/conda-forge/nco-feedstock). I have no conda expertise, but I'm happy to help if other questions arise...

**Comment by ocefpaf** [comment]
> if I try to install nco via conda inside of uvcdat, I have a conflict, I think this is due to nco being built against old hdf5/netcdf.

I am not sure that you mean by inside `uvcdat`. Is that a conda channel with `uvcdat`? Or another python distribution that has `uvcdat`?

> It appears that nco will downgrade our hdf5 but not our netcdf

Indeed. All `conda-forge` packages are pinned to versions that are consistent with each other.
See https://github.com/conda-forge/nco-feedstock/blob/master/recipe/meta.yaml#L20-L22

> The following packages will be SUPERCEDED by a higher-priority channel:
    hdf5:   1.8.16-UVCDAT uvcdat      --> 1.8.15.1-2

That is interesting though b/c `conda-forge`'s version is pinned against `hdf5 1.8.17.*` and conda is not respecting that. How many channels do you have in your `.condarc` file? The message suggests that another channel has higher priority and that may be the source of your problems.

> It goes through the motions but then cannot function

That is probably happening b/c conda is preferring to honor the channel priority instead of the pinning :unamused: (A bad design IMO.)

Either way mixing channels is not a good idea. You can either use the `nco` feedstock recipe to re-build `nco` "inside" `uvcdat`, with the same dependencies versions as the rest of the `uvcdat` stack,  or you can submit a recipe for `uvcdat` to [`conda-forge`](https://github.com/conda-forge/staged-recipes). It will be very unlikely that the dependencies versions would. Note that `nco` depencies are quite complex and with constant ABI changes so a consistent stack can only be obtained by building everything within the same environment like `conda-forge` or the `defaults` channels.

**Comment by doutriaux1** [comment]
@czender I think that's the best solution, you might as well up the version to the latest ones at this time (I think hdf5 is now at 1.8.17)

**Comment by doutriaux1** [comment]
@ocefpaf it seems to be mac related (i just tried on Linux and it looks like it worked). Here are my steps:
```
conda create -n uvcdat_nco cdms2 -c uvcdat/label/nightly -c uvcdat
source activate uvcdat_nco
conda install nco -c conda-forge
ncks
```
gives me:
```
ncks
dyld: Library not loaded: @rpath/libhdf5.10.dylib
  Referenced from: /Users/doutriaux1/anaconda2/envs/nco/lib/libnetcdf.7.dylib
  Reason: Incompatible library version: libnetcdf.7.dylib requires version 12.0.0 or later, but libhdf5.10.dylib provides version 11.0.0
```

**Comment by doutriaux1** [comment]
@ocefpaf hasn't support for conda-forge just been discontinued by continuum?

**Comment by ocefpaf** [comment]
> @ocefpaf hasn't support for conda-forge just been discontinued by continuum?

Not sure what you mean by "discontinued by continuum." Conda-forge is not, and has never been, a continuum (the company) service. We do make use of their open source tools (`conda` and `conda-build` mostly), and they do graciously grant us space to store the packages for free in `anaconda.org`. (See myth 8 -- last paragraph of https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/)

**Comment by doutriaux1** [comment]
I'm refering to this blog: https://www.continuum.io/blog/developer-blog/powering-down-the-anaconda-build-ci-system

**Comment by doutriaux1** [comment]
I misread it. It's their stuff that's shutting down. My bad. I'll take a look a putting uvcdat in conda-forge

**Comment by ocefpaf** [comment]
> I'm refering to this blog: https://www.continuum.io/blog/developer-blog/powering-down-the-anaconda-build-ci-system

That blog says exactly the opposite.  Continuum is shutting down their own CI service in favor of the community efforts in `conda-forge`.

> We feel that the Anaconda community efforts around Conda-Forge (along with Travis CI, CircleCI, and Appveyor) are in a better position to deliver reliable continuous integration services compared to our internal efforts with Anaconda Build.

**Comment by doutriaux1** [comment]
they actually show how to use conda-forge at: https://www.continuum.io/blog/developer-blog/anaconda-build-migration-conda-forge

**Comment by czender** [comment]
@ocefpaf does the conda-forge install of nco successfully pull in esmf? there was an issue with that a few months ago. any updates?

**Comment by ocefpaf** [comment]
> @ocefpaf does the conda-forge install of nco successfully pull in esmf? there was an issue with that a few months ago. any updates?

It should be all set now. Let me know if you find any issues.

**Comment by czender** [comment]
excellent. thanks for all your help!

**Comment by czender** [comment]
Everything works for me with conda-forge, which provides, BTW, a more complete NCO package than any other distribution (because it comes with all the usual goodies plus ESMF_RegridWeightGen)

**Comment by doutriaux1** [comment]
That's great!
